apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-creator-binding
  namespace: ingress-petstoreservices
subjects:
- kind: ServiceAccount
  name: ingress-nginx
  namespace: ingress-petstoreservices
roleRef:
  kind: Role
  name: configmap-creator
  apiGroup: rbac.authorization.k8s.io
