name: Pet Store Product Service CI/CD to Azure Container Registry
  
env:
  AZURE_CONTAINER_REGISTRY: takapetstorecr.azurecr.io
  AZURE_CONTAINER_REGISTRY_USERNAME: takapetstorecr
  
on:
  push:
    branches:
      - main
    paths:
      - petstore/petstoreproductservice/**
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checking the file system listing for Pet Store Product Service
      run: |
        ls -al
    - name: Update the version.json
      run: echo -n -e "{\"version\":\"${{ github.sha }}\",\"date\":\"$(date '+%m-%d-%Y %H:%M:%S')\"}" > petstore/petstoreproductservice/src/main/resources/version.json
    - run: cat petstore/petstoreproductservice/src/main/resources/version.json
    - uses: actions/setup-java@v2
      name: Building Pet Store Pet Service with Java 8
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Run Maven build
      run: mvn -f petstore/petstoreproductservice/pom.xml --batch-mode --update-snapshots verify
    - name: Upload Maven build artifact
      uses: actions/upload-artifact@v1
      with:
        name: artifact
        path: petstore/petstoreproductservice/target/petstoreproductservice-0.0.1-SNAPSHOT.jar
    - uses: azure/docker-login@v1
      name: Build Docker image
      with:
        login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
        username: ${{ env.AZURE_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.PETSTORECRSECRET }}
    - name: Push Docker image to Azure Container Registry    
      run: |
        docker build petstore/petstoreproductservice -t ${{env.AZURE_CONTAINER_REGISTRY}}/petstoreproductservice:latest -t ${{ env.AZURE_CONTAINER_REGISTRY }}/petstoreproductservice:${{ github.sha }}
        docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/petstoreproductservice:${{ github.sha }}
        docker push  ${{ env.AZURE_CONTAINER_REGISTRY }}/petstoreproductservice:latest
      
