name: Pet Store Pet Service CI/CD to Azure Container Registry
  
env:
  AZURE_CONTAINER_REGISTRY: takapetstorecr.azurecr.io
  AZURE_CONTAINER_REGISTRY_USERNAME: takapetstorecr
  
on:
  push:
    branches:
      - main
    paths:
      - petstore/petstorepetservice/**
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checking the file system listing for Pet Store Pet Service
      run: |
        ls -al
    - name: Update the version.json
      run: echo -n -e "{\"version\":\"${{ github.sha }}\",\"date\":\"$(date '+%m-%d-%Y %H:%M:%S')\"}" > petstore/petstorepetservice/src/main/resources/version.json
    - run: cat petstore/petstorepetservice/src/main/resources/version.json
    - uses: actions/setup-java@v2
      name: Building Pet Store Pet Service with Java 1.8
      with:
        java-version: '1.8'
        distribution: 'adopt'
    - name: Run Maven build
      run: mvn -f petstore/petstorepetservice/pom.xml --batch-mode --update-snapshots verify
    - name: Upload Maven build artifact
      uses: actions/upload-artifact@v1
      with:
        name: artifact
        path: petstore/petstorepetservice/target/petstorepetservice-0.0.1-SNAPSHOT.jar
    - uses: azure/docker-login@v1
      name: Build Docker image
      with:
        login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
        username: ${{ env.AZURE_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.PETSTORECRSECRET }}
    - name: Push Docker image to Azure Container Registry    
      run: |
        docker build petstore/petstorepetservice -t ${{env.AZURE_CONTAINER_REGISTRY}}/petstorepetservice:latest -t ${{ env.AZURE_CONTAINER_REGISTRY }}/petstorepetservice:${{ github.sha }}
        docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/petstorepetservice:${{ github.sha }}
        docker push  ${{ env.AZURE_CONTAINER_REGISTRY }}/petstorepetservice:latest
      
